### PR TITLE
Remove try/catch block in upgrade

### PR DESCRIPTION
**Pull request by itai-huddly**
Having a try/catch block causes loss of meaningful error messages. Compare the error given before getting rid of the try/catch block:

```
2020-11-26 | 16:4:48:464 | INFO | Boxfish PKG Upgrader | Calculating checksum...
2020-11-26 | 16:4:48:672 | DEBUG | Boxfish PKG Upgrader | Flashing APPLICATION
2020-11-26 | 16:4:48:673 | ERROR | Boxfish PKG Upgrader | Boxfish camera upgrade failed
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object
    at validChunk (_stream_writable.js:263:10)
    at WriteStream.Writable.write (_stream_writable.js:297:21)
    at DefaultLogger.error (/home/itai/kubicam-sw/tools/clijs/utils/default-logger.js:56:22)
    at BoxfishUpgrader.<anonymous> (/home/itai/kubicam-sw/tools/clijs/node_modules/@huddly/sdk/src/components/upgrader/boxfishUpgrader.ts:450:20)
    at Generator.throw (<anonymous>)
    at rejected (/home/itai/kubicam-sw/tools/clijs/node_modules/@huddly/sdk/lib/src/components/upgrader/boxfishUpgrader.js:6:65)
```

and after getting rid of the block:

```
2020-11-26 | 16:17:38:785 | INFO | Boxfish PKG Upgrader | Calculating checksum...
2020-11-26 | 16:17:38:992 | DEBUG | Boxfish PKG Upgrader | Flashing APPLICATION
TypeError: Cannot read property 'offset' of undefined
    at BoxfishHpk.getData (/home/itai/kubicam-sw/tools/clijs/node_modules/@huddly/sdk/src/components/upgrader/boxfishhpk.ts:50:51)
    at BoxfishUpgrader.<anonymous> (/home/itai/kubicam-sw/tools/clijs/node_modules/@huddly/sdk/src/components/upgrader/boxfishUpgrader.ts:371:31)
    at Generator.next (<anonymous>)
    at /home/itai/kubicam-sw/tools/clijs/node_modules/@huddly/sdk/lib/src/components/upgrader/boxfishUpgrader.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/itai/kubicam-sw/tools/clijs/node_modules/@huddly/sdk/lib/src/components/upgrader/boxfishUpgrader.js:4:12)
    at BoxfishUpgrader.flashImage (/home/itai/kubicam-sw/tools/clijs/node_modules/@huddly/sdk/lib/src/components/upgrader/boxfishUpgrader.js:382:16)
    at BoxfishUpgrader.<anonymous> (/home/itai/kubicam-sw/tools/clijs/node_modules/@huddly/sdk/src/components/upgrader/boxfishUpgrader.ts:426:16)
    at Generator.next (<anonymous>)
    at fulfilled (/home/itai/kubicam-sw/tools/clijs/node_modules/@huddly/sdk/lib/src/components/upgrader/boxfishUpgrader.js:5:58)
```

### CODE REVIEW

**Comment by jontore** [comment]
Unfortunately we need the UPGRADE_FAILED event, we also don't want to expose too much internal logging in the logs.

**Comment by kristofferkoch** [comment]
Hm, maybe its possible to write the catch so that the Exception gets rethrown without so much information loss? The two stack traces here are quite night and day, where the second actually told us what was wrong.

I don't quite get the argument about exposing too much?

**Comment by jontore** [comment]
These logs are exposed to external consumers of the sdk.

**Comment by jontore** [comment]
We can probably use this, https://nodejs.org/api/errors.html#errors_error_stack, maybe add it to a lower logging level

**Comment by brikendr** [comment]
@itai-huddly please update this PR when you get the chance

**Pull request closed without merging**
